apiVersion: v1
kind: Service
metadata:
  labels:
    app: demok8s
  name: demok8s
spec:
  ports:
    - name: 8080-8080
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: demok8s
  type: NodePort
status:
  loadBalancer: {}
